export const SET_TARGET_ASSET = "SET_TARGET_ASSET"
export const FETCH_ASSET_DATA_REQUESTED = "FETCH_ASSET_DATA_REQUESTED"
export const FETCH_ASSET_DATA_SUCCEEDED = "FETCH_ASSET_DATA_SUCCEEDED"
export const FETCH_ASSET_DATA_FAILED = "FETCH_ASSET_DATA_FAILED"

export const CLEAN_QUERY = "CLEAN_QUERY"
export const START_SEARCH = "START_SEARCH"
export const FINISH_SEARCH = "FINISH_SEARCH"
export const UPDATE_SELECTION = "UPDATE_SELECTION"